name: bus-impl-v2-ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read
  attestations: write
  id-token: write
  security-events: write
  pull-requests: read

jobs:
  audit:
    uses: VigilioYonatan/vigilio-platform-actions/.github/workflows/shared-governance-audit.yml@17deb75b6e2161415f6c82403579e6e02c76a64b

