name: bus-impl-v2-ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  application:
    uses: VigilioYonatan/vigilio-platform-actions/.github/workflows/shared-backend-node-nest-ci.yml@74ad35aeb42db1ffed5ed03527339aac28f700b8 # v1
    with:
      has-cdk: false
      has-openapi: true
      has-postgres: true
      run-aws-integration: true
      run-bdd: true
      run-e2e: true
      run-security-deep: true
      e2e-script: ${{ github.event_name == 'pull_request' && 'test:e2e:critical' || 'test:e2e' }}
      attest-artifact: ${{ github.event_name == 'push' }}
      gitops-bot-actor: ${{ vars.GITOPS_BOT_ACTOR || 'github-actions[bot]' }}
    secrets: inherit
